### ISSUE TITLE
MongoNetworkError: tlsv1 alert internal error

### ISSUE THREAD

**Issue by Yc020130** [idurar/idurar-erp-crm#1191]
C:\Users\16329\Desktop\idurar-erp-crm-master\backend>npm run setup

> idurar-erp-crm@4.1.0 setup
> node src/setup/setup.js

C:\Users\16329\Desktop\idurar-erp-crm-master\backend\node_modules\mongoose\node_modules\mongodb\lib\cmap\connect.js:379
            return new error_1.MongoNetworkError(error_1.MongoError.buildErrorMessage(err), { cause: err });
                   ^

MongoNetworkError: BCA40000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1590:SSL alert number 80

    at connectionFailureError (C:\Users\16329\Desktop\idurar-erp-crm-master\backend\node_modules\mongoose\node_modules\mongodb\lib\cmap\connect.js:379:20)
    at TLSSocket.<anonymous> (C:\Users\16329\Desktop\idurar-erp-crm-master\backend\node_modules\mongoose\node_modules\mongodb\lib\cmap\connect.js:285:22)
    at Object.onceWrapper (node:events:634:26)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  connectionGeneration: 6,
  [Symbol(errorLabels)]: Set(1) { 'ResetPool' },
  [cause]: [Error: BCA40000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1590:SSL alert number 80
  ] {
    library: 'SSL routines',
    reason: 'tlsv1 alert internal error',
    code: 'ERR_SSL_TLSV1_ALERT_INTERNAL_ERROR'
  }
}

Node.js v20.18.0

C:\Users\16329\Desktop\idurar-erp-crm-master\backend>npm run setup

> idurar-erp-crm@4.1.0 setup
> node src/setup/setup.js

C:\Users\16329\Desktop\idurar-erp-crm-master\backend\node_modules\mongoose\node_modules\mongodb\lib\cmap\connect.js:379
            return new error_1.MongoNetworkError(error_1.MongoError.buildErrorMessage(err), { cause: err });
                   ^

MongoNetworkError: 88D00000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1590:SSL alert number 80

    at connectionFailureError (C:\Users\16329\Desktop\idurar-erp-crm-master\backend\node_modules\mongoose\node_modules\mongodb\lib\cmap\connect.js:379:20)
    at TLSSocket.<anonymous> (C:\Users\16329\Desktop\idurar-erp-crm-master\backend\node_modules\mongoose\node_modules\mongodb\lib\cmap\connect.js:285:22)
    at Object.onceWrapper (node:events:634:26)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  connectionGeneration: 1,
  [Symbol(errorLabels)]: Set(1) { 'ResetPool' },
  [cause]: [Error: 88D00000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1590:SSL alert number 80
  ] {
    library: 'SSL routines',
    reason: 'tlsv1 alert internal error',
    code: 'ERR_SSL_TLSV1_ALERT_INTERNAL_ERROR'
  }
}

Node.js v20.18.0

respect Sir
After i have changed the mongoDB url,I meet this bug,i can not use the "npm run setup" to deploy the project，there is the bug log,can you help me to solve the bug?I am waiting for your answer!
Yours

**Comment by SheiklAR** [comment]
Did you add the IP address of the deployment server in the network access settings, if you use MongoDB atlas?

**Comment by luisfelix-93** [comment]
I think you need to review your database's TSL/SSL settings
